plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '5.1.+'
}

group = 'com.drowselab'
version = '1.0.0'
archivesBaseName = 'kid-gun-1412'

minecraft {
    mappings channel: 'official', version: '1.19.2'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    mavenCentral()
    maven { url = "https://maven.minecraftforge.net/" }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.19.2-43.2.0'
    implementation fg.deobf("com.example.tacz:TACZ:1.0.0") // TACZの依存を追加
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    sourceCompatibility = '17'
    targetCompatibility = '17'
}
