modLoader="javafml"
loaderVersion="[1.19.2,)"
[[mods]]
modId="kid_gun_1412"
version="1.0.0"
displayName="Kid Gun 1412"
description="A mod that adds custom guns like Trump Gun."
dependencies = [
    { modId="tacz", mandatory=true, versionRange="[1.0.0,)", ordering="NONE", side="BOTH" }
]
