name: Java CI with Gradle

on:
  push:
    branches: [ "1.19.2" ]
  pull_request:
    branches: [ "1.19.2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: List files for debugging
      run: ls -la

    - name: Verify gradlew file exists
      run: test -f ./gradlew || echo "gradlew not found"

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build
